
export var tweets = [
  { url: 'https://twitter.com/Nigel_Farage/status/734660441868238848',
  author_name: 'Nigel Farage',
  author_url: 'https://twitter.com/Nigel_Farage',
  html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The passion is on the Leave side. I&#39;m optimistic that on June 23rd the UK will back <a href="https://twitter.com/hashtag/Brexit?src=hash">#Brexit</a>. <a href="https://t.co/ovylXIco0M">https://t.co/ovylXIco0M</a></p>&mdash; Nigel Farage (@Nigel_Farage) <a href="https://twitter.com/Nigel_Farage/status/734660441868238848">May 23, 2016</a></blockquote>\n<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>',
  width: 550,
  type: 'rich',
  cache_age: '3153600000',
  provider_name: 'Twitter',
  provider_url: 'https://twitter.com',
  height: null,
  version: '1.0' },
{ url: 'https://twitter.com/TheEconomist/status/734489027110445057',
  author_name: 'The Economist',
  author_url: 'https://twitter.com/TheEconomist',
  html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">British farmers benefit from EU funding but they back Brexit. Why? <a href="https://t.co/ZZVG6KRj7S">https://t.co/ZZVG6KRj7S</a> <a href="https://t.co/APbNTn9EeS">pic.twitter.com/APbNTn9EeS</a></p>&mdash; The Economist (@TheEconomist) <a href="https://twitter.com/TheEconomist/status/734489027110445057">May 22, 2016</a></blockquote>\n<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>',
  width: 550,
  type: 'rich',
  cache_age: '3153600000',
  provider_name: 'Twitter',
  provider_url: 'https://twitter.com',
  height: null,
  version: '1.0' },
{ url: 'https://twitter.com/tnewtondunn/status/734330319986429952',
  author_name: 'Tom Newton Dunn',
  author_url: 'https://twitter.com/tnewtondunn',
  html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Head of CBI <a href="https://twitter.com/cbicarolyn">@cbicarolyn</a> agrees UK may eventually prosper under Brexit: &quot;I accept that over the long term, the economy would adapt&quot; <a href="https://twitter.com/hashtag/bbcsp?src=hash">#bbcsp</a></p>&mdash; Tom Newton Dunn (@tnewtondunn) <a href="https://twitter.com/tnewtondunn/status/734330319986429952">May 22, 2016</a></blockquote>\n<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>',
  width: 550,
  type: 'rich',
  cache_age: '3153600000',
  provider_name: 'Twitter',
  provider_url: 'https://twitter.com',
  height: null,
  version: '1.0' },
{ url: 'https://twitter.com/TheEconomist/status/734427114578006017',
  author_name: 'The Economist',
  author_url: 'https://twitter.com/TheEconomist',
  html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Agriculture could lose out, but most farmers seems to back Brexit <a href="https://t.co/6RjnLrPSva">https://t.co/6RjnLrPSva</a> <a href="https://t.co/vH71COlXKW">pic.twitter.com/vH71COlXKW</a></p>&mdash; The Economist (@TheEconomist) <a href="https://twitter.com/TheEconomist/status/734427114578006017">May 22, 2016</a></blockquote>\n<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>',
  width: 550,
  type: 'rich',
  cache_age: '3153600000',
  provider_name: 'Twitter',
  provider_url: 'https://twitter.com',
  height: null,
  version: '1.0' },
{ url: 'https://twitter.com/timothy_stanley/status/734673036373286912',
  author_name: 'Tim Stanley',
  author_url: 'https://twitter.com/timothy_stanley',
  html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Steve Hilton sums up the case for Brexit well. Little more to say. <a href="https://t.co/8qiFyTp9LS">pic.twitter.com/8qiFyTp9LS</a></p>&mdash; Tim Stanley (@timothy_stanley) <a href="https://twitter.com/timothy_stanley/status/734673036373286912">May 23, 2016</a></blockquote>\n<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>',
  width: 550,
  type: 'rich',
  cache_age: '3153600000',
  provider_name: 'Twitter',
  provider_url: 'https://twitter.com',
  height: null,
  version: '1.0' },
{ url: 'https://twitter.com/haveigotnews/status/734707336154107904',
  author_name: 'HaveIGotNewsForYou',
  author_url: 'https://twitter.com/haveigotnews',
  html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Nigel Farage&#39;s Brexit Bus gets lost on way to Dagenham due to UK being a country he no longer recognises.</p>&mdash; HaveIGotNewsForYou (@haveigotnews) <a href="https://twitter.com/haveigotnews/status/734707336154107904">May 23, 2016</a></blockquote>\n<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>',
  width: 550,
  type: 'rich',
  cache_age: '3153600000',
  provider_name: 'Twitter',
  provider_url: 'https://twitter.com',
  height: null,
  version: '1.0' },
{ url: 'https://twitter.com/guardian/status/734681855736303616',
  author_name: 'The Guardian',
  author_url: 'https://twitter.com/guardian',
  html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Study confirms that the national press is biased in favour of Brexit <a href="https://t.co/ORRIb0KPgl">https://t.co/ORRIb0KPgl</a></p>&mdash; The Guardian (@guardian) <a href="https://twitter.com/guardian/status/734681855736303616">May 23, 2016</a></blockquote>\n<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>',
  width: 550,
  type: 'rich',
  cache_age: '3153600000',
  provider_name: 'Twitter',
  provider_url: 'https://twitter.com',
  height: null,
  version: '1.0' },
{ url: 'https://twitter.com/johnprescott/status/734298703754842113',
  author_name: 'John Prescott',
  author_url: 'https://twitter.com/johnprescott',
  html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Stop demonising refugees to boost Brexit. They don&#39;t come for a life on benefits. They want the benefit of life. <a href="https://t.co/8zcTgxnZKC">https://t.co/8zcTgxnZKC</a></p>&mdash; John Prescott (@johnprescott) <a href="https://twitter.com/johnprescott/status/734298703754842113">May 22, 2016</a></blockquote>\n<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>',
  width: 550,
  type: 'rich',
  cache_age: '3153600000',
  provider_name: 'Twitter',
  provider_url: 'https://twitter.com',
  height: null,
  version: '1.0' },
{ url: 'https://twitter.com/LordAshcroft/status/734566283916771332',
  author_name: 'Lord Ashcroft',
  author_url: 'https://twitter.com/LordAshcroft',
  html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Why we MUST quit the EU, by David Cameron&#39;s guru Steve Hilton . The PM will love this... do retweet <a href="https://t.co/f95K1hQiJj">https://t.co/f95K1hQiJj</a></p>&mdash; Lord Ashcroft (@LordAshcroft) <a href="https://twitter.com/LordAshcroft/status/734566283916771332">May 23, 2016</a></blockquote>\n<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>',
  width: 550,
  type: 'rich',
  cache_age: '3153600000',
  provider_name: 'Twitter',
  provider_url: 'https://twitter.com',
  height: null,
  version: '1.0' },
{ url: 'https://twitter.com/nytimes/status/734640765184450560',
  author_name: 'The New York Times',
  author_url: 'https://twitter.com/nytimes',
  html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">&quot;Brexit&quot;: A feel-good vote that could sink Britain’s economy <a href="https://t.co/tUCB5SOwpM">https://t.co/tUCB5SOwpM</a></p>&mdash; The New York Times (@nytimes) <a href="https://twitter.com/nytimes/status/734640765184450560">May 23, 2016</a></blockquote>\n<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>',
  width: 550,
  type: 'rich',
  cache_age: '3153600000',
  provider_name: 'Twitter',
  provider_url: 'https://twitter.com',
  height: null,
  version: '1.0' },
{ url: 'https://twitter.com/TheEconomist/status/734713007339606016',
  author_name: 'The Economist',
  author_url: 'https://twitter.com/TheEconomist',
  html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The financial-services industry would be one of the biggest losers from Brexit <a href="https://t.co/21DjAj9gBr">https://t.co/21DjAj9gBr</a> <a href="https://t.co/8DOO2klNaY">pic.twitter.com/8DOO2klNaY</a></p>&mdash; The Economist (@TheEconomist) <a href="https://twitter.com/TheEconomist/status/734713007339606016">May 23, 2016</a></blockquote>\n<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>',
  width: 550,
  type: 'rich',
  cache_age: '3153600000',
  provider_name: 'Twitter',
  provider_url: 'https://twitter.com',
  height: null,
  version: '1.0' },
{ url: 'https://twitter.com/FraserNelson/status/734652403568496640',
  author_name: 'Fraser Nelson',
  author_url: 'https://twitter.com/FraserNelson',
  html: '<blockquote class="twitter-tweet"><p lang="en" dir="ltr">And let&#39;s remember, Osborne fabricated his £4,300 cost-of-Brexit figure. Here&#39;s how: <a href="https://t.co/t7EpvIGCid">https://t.co/t7EpvIGCid</a></p>&mdash; Fraser Nelson (@FraserNelson) <a href="https://twitter.com/FraserNelson/status/734652403568496640">May 23, 2016</a></blockquote>\n<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>',
  width: 550,
  type: 'rich',
  cache_age: '3153600000',
  provider_name: 'Twitter',
  provider_url: 'https://twitter.com',
  height: null,
  version: '1.0' }]
